# Minimal Quick Test
# Using pred-len 96 (4 days hourly forecast) for meaningful results

--rounds 10 --num-clients 5 --local-epochs 1 --lr 0.0002 --pred-len 36 --dropout 0.3
--rounds 10 --num-clients 5 --local-epochs 1 --lr 0.0002 --pred-len 36 --dropout 0.2